export interface MemeResponse {
  url: string;
  title: string;
  date: Date;
  author: string;
  sub: string;
  post: string;
}

export type GIFResponse = string;

// Generated by https://quicktype.io

export interface LyricsAPI {
  artist: string;
  artist_id: number;
  album: string;
  album_ids: string;
  album_year: string;
  name: string;
  lyrics: string;
  search_str: string;
  album_art: string;
  popularity: number;
  singalong: Singalong[];
  meta: Meta;
  id: string;
  search_score: number;
  url: string;
}

export interface Meta {
  spotify: Deezer;
  deezer: Deezer;
  other: Other;
}

export interface Deezer {
  artists: string[];
  track: null | string;
  album: string;
}

export interface Other {
  gain: number;
  bpm: number;
  musicbrainz: Musicbrainz;
}

export interface Musicbrainz {
  artist: null;
}

export interface Singalong {
  lrc_timestamp: string;
  milliseconds: string;
  duration: string;
  line: string;
}
